# storageclass: azurefile-csi-0777
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-csi-0777
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
  - mfsymlinks
  - nobrl
parameters:
  skuName: Standard_LRS   # or Premium_LRS
---
# pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-shared-pvc
  namespace: spark-operator
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: azurefile-csi-0777
