apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-run-now
  namespace: management
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: docker.io/library/spark:3.5.1
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.5.1"
  timeToLiveSeconds: 60
  restartPolicy:
    type: Never
  sparkConf:
    "spark.hadoop.hadoop.security.authentication": "Simple"
  driver:
    cores: 1
    coreRequest: "100m"
    coreLimit: "500m"
    memory: "512m"
    memoryOverhead: "256m"
    serviceAccount: spark-operator-controller
  executor:
    instances: 1
    cores: 1
    coreRequest: "100m"
    coreLimit: "500m"
    memory: "512m"
    memoryOverhead: "256m"
